import {
  Home,
  Members,
  Teams,
  Appointment,
  Report,
  Categories,
  SubCategories,
  LabDoctor,
  Taxes,
  Plans,
  Doctor,
  Transactions,
  Profile,
  LabText,
  Patients,
  TypeSample,
  Settings,
  Hostel,
  Certificate,
  Notice,
  Authority,
  Library,
  Result,
  Scholar,
  Assignm,
} from "../Shared/Icons";

export const sidebarLink = [
  {
    id: 1,
    title: "Main Menus",
    children: [
      { id: 1, title: "Dashboard", path: "/", icon: Home },
      {
        id: 2,
        title: "Administration",
        path: "/",
        icon: Profile,
      },
      { id: 3, title: "All Courses", path: "/", icon: Categories },
      { id: 4, title: "Schedule", path: "/", icon: Plans },
      { id: 5, title: "All Events", path: "/", icon: Home },
      { id: 6, title: "Notice Board", path: "/", icon: Notice },
      { id: 7, title: "Study Materials", path: "/", icon: TypeSample },
      { id: 8, title: "All Teachers", path: "/", icon: Home },
      { id: 9, title: "All Stuff", path: "/", icon: Members },
      { id: 10, title: "All Students", path: "/", icon: Teams },
      { id: 11, title: "Authorities & Committees", path: "/", icon: Authority },
      { id: 12, title: "Invoice", path: "/", icon: Taxes },
      { id: 13, title: "Attendance", path: "/", icon: Appointment },
      { id: 14, title: "Admission", path: "/", icon: Home },
      { id: 15, title: "Settings", path: "/", icon: Settings },
      { id: 16, title: "Hostel Management", path: "/", icon: Hostel },
      { id: 17, title: "Library Management", path: "/", icon: Library },
      { id: 18, title: "Assignments", path: "/", icon: Assignm },
      { id: 19, title: "Scholarships", path: "/", icon: Scholar },
      { id: 20, title: "Career Management", path: "/", icon: Doctor },
      { id: 21, title: "HR Management", path: "/", icon: Patients },
      { id: 22, title: "Reports", path: "/", icon: Report },
      { id: 23, title: "Stock Store", path: "/", icon: Transactions },
      { id: 24, title: "Laboratory Management", path: "/", icon: LabText },
      { id: 25, title: "Results", path: "/", icon: Result },
      { id: 26, title: "Certificates", path: "/", icon: Certificate },
    ],
  },
];
