import {
  Home,
  Members,
  Teams,
  Appointment,
  Report,
  Categories,
  SubCategories,
  LabDoctor,
  Taxes,
  Plans,
  Doctor,
  Transactions,
  Profile,
  LabText,
  Patients,
  TypeSample,
  Settings,
  Hostel,
  Certificate,
  Notice,
  Authority,
  Library,
  Result,
  Scholar,
  Assignm,
  Admin,
  Event,
  Edit,
  Course,
  Stocks,
  Calender,
  Teach,
  Staff,
} from "../Shared/Icons";

export const sidebarLink = [
  {
    id: 1,
    title: "Main Menus",
    children: [
      { id: 1, title: "Dashboard", path: "/", icon: Home },
      { id: 2, title: "Admission", path: "/", icon: Edit },
      { id: 3, title: "Events", path: "/", icon: Event },
      { id: 4, title: "Courses", path: "/", icon: Course },
    ],
  },
  {
    id: 2,
    title: "Manage Organization",
    children: [
      {
        id: 1,
        title: "Administration",
        path: "/",
        icon: Admin,
      },
      { id: 2, title: "Authority & Committee", path: "/", icon: Authority },
      { id: 3, title: "Hostel", path: "/", icon: Hostel },
      { id: 4, title: "Laboratory", path: "/", icon: LabText },
      { id: 5, title: "Library", path: "/", icon: Library },
    ],
  },
  {
    id: 3,
    title: "Manage Internals",
    children: [
      { id: 1, title: "Teachers", path: "/", icon: Teach },
      { id: 2, title: "Stuffs", path: "/", icon: Staff },
      { id: 3, title: "Human Resources", path: "/", icon: Patients },
      { id: 4, title: "Study Materials", path: "/", icon: TypeSample },
      { id: 5, title: "Schedules", path: "/", icon: Calender },
      { id: 6, title: "Reports", path: "/", icon: Report },
      { id: 7, title: "Stock Store", path: "/", icon: Stocks },
      { id: 8, title: "Notice Board", path: "/", icon: Notice },
      { id: 9, title: "Invoice", path: "/", icon: Taxes },
      { id: 10, title: "Career", path: "/", icon: Doctor },
    ],
  },
  {
    id: 4,
    title: "Manage Students",
    children: [
      { id: 1, title: "Student Informations", path: "/", icon: Teams },
      { id: 2, title: "Assignments", path: "/", icon: Assignm },
      { id: 3, title: "Scholarships", path: "/", icon: Scholar },
      { id: 4, title: "Results", path: "/", icon: Result },
      { id: 5, title: "Certificates", path: "/", icon: Certificate },
      { id: 7, title: "Attendance", path: "/", icon: Appointment },
    ],
  },
  {
    id: 5,
    title: "Manage Others",
    children: [
      { id: 1, title: "Settings", path: "/", icon: Settings },
      { id: 2, title: "Profile", path: "/", icon: Profile },
    ],
  },
];
